/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Yaryna
 */
public class GenerateMultipleRandomFiles extends javax.swing.JDialog {

    private MainView parent;
    private int numOffiles;
    private String directoryName;
    private int maxSalesmen;
    private int maxPoints;
    
    /**
     * Creates new form GenerateMultipleRandomFiles
     */
    public GenerateMultipleRandomFiles(java.awt.Frame p, boolean modal,MainView parent ) {
        super(p, modal);
        this.parent = parent;
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numberOFfilesjTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        directoryChooser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        salesmenMaxjTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pointsMaxjTextField2 = new javax.swing.JTextField();
        ButtonjPanel = new javax.swing.JPanel();
        generateButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generate multiple random files");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Amount  of random files : ");
        jPanel1.add(jLabel1);

        numberOFfilesjTextField1.setText("1");
        jPanel1.add(numberOFfilesjTextField1);

        jLabel2.setText("Choose location for a directory with files: ");
        jPanel1.add(jLabel2);

        directoryChooser.setText("...");
        directoryChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryChooserActionPerformed(evt);
            }
        });
        jPanel1.add(directoryChooser);

        jLabel3.setText("number of salesman : ");
        jPanel1.add(jLabel3);

        salesmenMaxjTextField1.setText("3");
        jPanel1.add(salesmenMaxjTextField1);

        jLabel4.setText("number of points : ");
        jPanel1.add(jLabel4);

        pointsMaxjTextField2.setText("10");
        jPanel1.add(pointsMaxjTextField2);

        getContentPane().add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        ButtonjPanel.setBackground(new java.awt.Color(0, 204, 204));
        ButtonjPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 204, 204)));
        ButtonjPanel.setLayout(new java.awt.GridLayout(0, 2, 20, 40));

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        ButtonjPanel.add(generateButton);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ButtonjPanel.add(jButton2);

        getContentPane().add(ButtonjPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
           if(directoryName!=null){
               this.numOffiles = Integer.parseInt(this.numberOFfilesjTextField1.getText());
               this.maxPoints = Integer.parseInt(this.pointsMaxjTextField2.getText());
               this.maxSalesmen = Integer.parseInt(this.salesmenMaxjTextField1.getText());
               this.parent.generateAndSaveFiles(this.numOffiles,this.directoryName,this.maxPoints,this.maxSalesmen);
           }
           this.setVisible(false);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Cancel Button
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void directoryChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryChooserActionPerformed
      this.directoryName =  this.parent.getDirectoryToSaveRandomFilesInto();
    }//GEN-LAST:event_directoryChooserActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonjPanel;
    private javax.swing.JButton directoryChooser;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numberOFfilesjTextField1;
    private javax.swing.JTextField pointsMaxjTextField2;
    private javax.swing.JTextField salesmenMaxjTextField1;
    // End of variables declaration//GEN-END:variables
}
