/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;

/**
 *
 * @author Krzysztof
 */
public class InputDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form InputDataPanel
     */
    public InputDataPanel(MainView parentView) {
        initComponents();
        this.setMaximumSize(new Dimension(400,60));
    }

    public int getSelectedMetric(){
        return this.metricCombobox.getSelectedIndex();
        /* 0 eucledian
           1 distance 
           2 time
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        metricCombobox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jLabel7.setText("Number of salesmen :");
        add(jLabel7);

        jTextField1.setText("2");
        add(jTextField1);

        jLabel2.setText("Used metric : ");
        add(jLabel2);

        metricCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eucledian", "Distance", "Time" }));
        add(metricCombobox);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox metricCombobox;
    // End of variables declaration//GEN-END:variables

    public int getSalesmanCount() {
        int i = 0;
        try{
                i = Integer.parseInt(this.jTextField1.getText());
        }
        catch(Exception e){}
        return i ;
    }
}
