/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Point2D;
import java.io.File;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.DefaultMapController;
import org.openstreetmap.gui.jmapviewer.JMapViewer;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;
import org.openstreetmap.gui.jmapviewer.interfaces.MapMarker;
import org.openstreetmap.gui.jmapviewer.tilesources.OfflineOsmTileSource;

/**
 *
 * @author K
 */
public class MapPanel extends javax.swing.JPanel {

    private JMapViewer map ;
    private MainView parentView;
    private Timer mouseTimer;
    private boolean wasDoubleClick;
    /**
     * Creates new form MapPanel
     */
    public MapPanel(MainView mv) {
        initComponents();
        parentView = mv;
        this.setLayout(new BorderLayout());
        this.setBackground(Color.red);
        init();
    }
    
    private void init(){
        map = new JMapViewer(); 
        //add map to fill the parent;
        constructMap();
        this.add(map,BorderLayout.CENTER);
    }
    
    
    private void constructMap(){
        try {
            // map.setTileSource(new OfflineOsmTileSource("file:///C:/Users/K/Desktop/DiplomaProject/DiplomaProject/TSPDiploma/Tiles",10,14));
            //corrected
            map.setTileSource(new OfflineOsmTileSource((new File("C:\\Users\\Krzysztof\\Desktop\\DiplomaProject\\DiplomaProject\\TSPDiploma\\Tiles").toURI().toURL()).toString(), 10, 14)); 
        } catch (MalformedURLException ex) {
            Logger.
                    getLogger(MapPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        map.setVisible(true);
        //map.setZoom(10); // set some zoom level (1-18 are valid)
        map.setSize(new Dimension(500,500));
        map.setBackground(Color.YELLOW);
        map.setDisplayPositionByLatLon(52.2297,21.0122, 10); //center in warsaw 
        
        
        //override mouse clicked method
        new DefaultMapController(map) {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount()== 2 ) {
                       System.out.println("double click");
                       wasDoubleClick = true;
                }
                else {
                    Integer timerinterval = (Integer)Toolkit.getDefaultToolkit().getDesktopProperty("awt.multiClickInterval");
                    mouseTimer = new Timer(timerinterval.intValue(), new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            if (wasDoubleClick) {
                                wasDoubleClick = false; // reset flag
                            } else {
                                System.out.println( "  and it's a simple click!");
                                System.out.println(e.getPoint());
                                Coordinate coo = map.getPosition(e.getPoint());
                                System.out.println(coo);

                                MapMarkerDot marker = new MapMarkerDot(Color.CYAN,coo.getLat(),coo.getLon());
                                MapPanel.this.map.addMapMarker(marker);
                            }
                        }    
                    });
                    mouseTimer.setRepeats(false);
                    mouseTimer.start();
                }
            }
        };
    }
    
    
    //test
    public void mouseClicked(MouseEvent e) {

    if (e.getClickCount() == 2) {  
        System.out.println( "  and it's a double click!");
        wasDoubleClick = true;
    }else{
        
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
