/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author Krzysztof
 */
public class OptionsPanel extends javax.swing.JPanel {

    MainView parentView; 
    AlgorithmChoicesPanel algPanel;
    JScrollPane algOptionsScrollPane;
    
    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel(MainView pV) {
        initComponents();
        init();
        
        this.parentView = pV; 
        this.setBackground(Color.WHITE);
        this.setPreferredSize(new Dimension(400,300));
    }

    private void init(){
        algPanel = new AlgorithmChoicesPanel(parentView);
        algOptionsScrollPane = new JScrollPane();
        algOptionsScrollPane.add(algPanel);
        
        algPanel.setVisible(true);
        algOptionsScrollPane.setVisible(true);
        
        this.add(algPanel);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 204)));
        setLayout(new java.awt.GridLayout(5, 0, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
